### ISSUE TITLE
Refactor and provide spec tests for the changes in PR 301

### ISSUE THREAD

**Issue by gmcculloug** [ManageIQ/manageiq-content#315]
The main methods in PR https://github.com/ManageIQ/manageiq-content/pull/301 need to be broken down into smaller methods with proper testing.

cc @fdupont-redhat

**Comment by fdupont-redhat** [comment]
Spec tests are tracked in https://github.com/ManageIQ/manageiq-content/issues/360

**Comment by gmcculloug** [comment]
Closing in favor of Issue https://github.com/ManageIQ/manageiq-content/issues/360
