### ISSUE TITLE
Use this repo as a content library for also dialogs, policies, reports, dashboards, alerts , menus

### ISSUE THREAD

**Issue by vestival** [ManageIQ/manageiq-content#551]
As a user, I want to add content out of the box to the product instead of to the core repo

**Comment by vestival** [comment]
@skateman

**Comment by skateman** [comment]
@martinpovolny, would it be possible to make our above mentioned contents more pluggable?

**Comment by Fryguy** [comment]
Yes this is the intention with this repo.  I'm going to close this for now as it's really an umbrella request to just add more pluggable content, which we should identify via individual issues.
