### ISSUE TITLE
Test files should not invoke app's spec_helper

### ISSUE THREAD

**Issue by chrisarcand** [ManageIQ/manageiq-content#6]
Note for us for later, as it's not super important at the moment: We require the main application's spec_helper in `.rspec`. The tests here and on every other cut repo should not require that, as it is a coupling that could cause really weird behavior.

On the plus side, it introduces a way to be able to specify RSpec options from a single place (the main app). If that's something that could be useful, we should store that in an explicit block that is obviously intended, because the coupling here is not obvious from either end. 

cc/ @bdunne

**Comment by Fryguy** [comment]
I would expect each repo to have its own .rspec file so it can be tailored.  If we are bringing in ManageIQ's .rspec that's probably not a good thing.

**Comment by chrisarcand** [comment]
It's not that we're using MIQ's .rspec, but that we're literally requiring MIQ's spec_helper in this project's .rspec: https://github.com/ManageIQ/manageiq-content/blob/master/.rspec#L1

For extraction this is a dirty hack so you don't have to nitpick and figure out the exact things that need to be extracted for tests to run in a separate repo, but we shouldn't keep it this way.

**Comment by JPrause** [comment]
@tinaafitz is this still a valid issue? If yes, please remove the stale label. If not can you close.
If there's no update by next week, I'll be closing this issue.

**Comment by chrisarcand** [comment]
You [still require the main application's spec_helper here, yes.](https://github.com/ManageIQ/manageiq-content/blob/d9b262254cdc86a9fafda8d791ae13a0020d8a17/.rspec#L1)
