### ISSUE TITLE
Automatic placement can fail with Azure if required resources aren't available

### ISSUE THREAD

**Issue by djberg96** [ManageIQ/manageiq-content#627]
Currently if you try to use automatic placement during provisioning can fail with:

```
[----] I, [2020-01-08T12:55:55.783175 #16250:5b8f60]  INFO -- : Q-task_id([r7000000000014_miq_provision_7000000000014]) Starting Phase <provision_error>
[----] E, [2020-01-08T12:55:55.798704 #16250:5b8f60] ERROR -- : Q-task_id([r7000000000014_miq_provision_7000000000014]) MIQ(ManageIQ::Providers::Azure::CloudManager::Provision#provision_error) [[NoMethodError]: undefined method `ems_ref' for nil:NilClass] encountered during phase [prepare_provision]
[----] E, [2020-01-08T12:55:55.798786 #16250:5b8f60] ERROR -- : Q-task_id([r7000000000014_miq_provision_7000000000014]) /opt/rh/cfme-gemset/bundler/gems/cfme-providers-azure-efc7b57d34b3/app/models/manageiq/providers/azure/cloud_manager/provision/cloning.rb:166:in `build_nic_options'
```

Where line 166 of cloning.rb is `:subnet => {:id => cloud_subnet.ems_ref}`, but there is apparently no associated `cloud_subnet`.

https://gist.github.com/lfu/28a252599b3b7585638f8cc5ed323604

Originally spotted by @lfu 

As per @gmcculloug the best placement code is at https://github.com/ManageIQ/manageiq-content/blob/master/content/automate/ManageIQ/Cloud/VM/Provisioning/Placement.class/__methods__/best_fit_azure.rb

**Comment by djberg96** [comment]
As per discussions on gitter, we think this is happening because the list of eligible cloud subnets is returning nil.

**Comment by lfu** [comment]
@djberg96 I think automate is doing the right thing in my testing case as there is no subnet at that moment. cloning.rb should handle the case when the expected resource is nil. Azure itself can create all these resources when deploying an image.

**Comment by djberg96** [comment]
@lfu alright, i'll close this and stick the issue on the azure provider repo
